name: Build tables
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: create lumi tables
    steps:
    - uses: actions/checkout@v2    
    - name: Prepare
      run: |
        mkdir outputs
    # run the container with the script in the repository
    - name: Going to a container
      id: container
      run: |
        echo "brilcalc --help > my.out" > commands.sh
        docker run -v $(pwd):/mnt/vol -w /home/brilws gitlab-registry.cern.ch/cms-cloud/brilws-docker /bin/bash /mnt/vol/commands.sh
        echo ls -l  `ls -l `
        cp *.out outputs
    # upload output file
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: outputs/
   
