name: Build tables
on:
  - pull_request
jobs:
  job1:
    runs-on: ubuntu-latest
    name: create lumi tables
    steps:
    - uses: actions/checkout@v2
    - name: Check the runner
      run: |
        which docker
