name: Build tables
on:
  - pull_request
env:
  YEAR: 2015   
jobs:
  Lumi:
    runs-on: ubuntu-latest
    name: create lumi tables
    steps:
    - uses: actions/checkout@v2    
    - name: Prepare
      run: |
        mkdir outputs
    # Get the parameters for lumi listings
    - name: Get parameters
      run: |
        which python
        echo "Get parameters for $YEAR"
        python code/read_run_info.py Run2015D
    # run the container with the script in the repository
    - name: Get luminosity summary listings
      id: container
      run: |
        wget https://opendata.cern.ch/record/14210/files/Cert_13TeV_16Dec2015ReReco_Collisions15_25ns_JSON_v2.txt
        docker run -v $(pwd):/mnt/vol -w /home/brilws gitlab-registry.cern.ch/cms-cloud/brilws-docker /bin/bash /mnt/vol/commands.sh > my.out
        echo ls -l  `ls -l `
        cp *.out outputs
    # upload output file
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: outputs/
   
